/**
 * Central list of every public route in the app. E2E specs iterate this
 * so adding a new route to src/routes/ automatically extends the
 * animation, a11y, and reduced-motion regression coverage.
 */
export const PUBLIC_ROUTES = [
  "/",
  "/about",
  "/ambassador",
  "/ambassador/apply",
  "/ambassador/dashboard",
  "/become-a-sponsor",
  "/blog",
  "/certificates",
  "/cloud",
  "/code-of-conduct",
  "/contact",
  "/cookies",
  "/dashboard",
  "/dashboard/proposals",
  "/devops",
  "/faq",
  "/forgot-password",
  "/gallery",
  "/host",
  "/host/apply",
  "/host/success",
  "/leadership",
  "/login",
  "/open-source",
  "/partners",
  "/privacy",
  "/refund",
  "/register",
  "/reset-password",
  "/resources",
  "/schedule-call",
  "/security",
  "/sponsor",
  "/sponsor/dashboard",
  "/sponsor/success",
  "/terms",
  "/about_/brand",
  "/about_/community",
  "/about_/faq",
  "/about_/history",
  "/about_/mission",
  "/about_/origohost",
  "/about_/research",
  "/about_/vision",
  "/academy",
  "/cloud_/dedicated",
  "/cloud_/kubernetes",
  "/cloud_/vps",
  "/community",
  "/community_/ambassadors",
  "/community_/ambassadors_/apply",
  "/community_/chapters",
  "/community_/events",
  "/content-policy",
  "/contributors",
  "/ecosystem",
  "/editorial-policy",
  "/fact-checking",
  "/glossary",
  "/press",
  "/research-methodology",
  "/roadmap",
  "/topics_/ai",
  "/topics_/career",
  "/topics_/cyber-security",
  "/topics_/hackathons",
  "/topics_/programming",
  "/transparency-report",
  "/trust-center",
] as const;

/** Subset used for pixel-diff snapshots — heavier, so keep it small. */
export const VISUAL_ROUTES: Array<{ path: string; name: string }> = [
  { path: "/", name: "home" },
  { path: "/about", name: "about" },
  { path: "/community_/events", name: "events" },
  { path: "/contact", name: "contact" },
  { path: "/login", name: "login" },
];
