import type { Resource } from "./types";

export const resources: Resource[] = [
  {
    title: "Open source contribution checklist",
    slug: "open-source-contribution-checklist",
    type: "Guide",
    category: "Open Source",
    description:
      "The workflow used in the OrigoHOST open source sessions: choosing a project, scoping an issue and working with maintainers.",
    author: "OrigoHOST Open Source",
    date: "2026-07-20",
    readingTime: "6 min",
    tags: ["open-source", "contribution", "beginner"],
  },
  {
    title: "Engineering portfolio review checklist",
    slug: "engineering-portfolio-review-checklist",
    type: "Guide",
    category: "Career",
    description: "How reviewers evaluate a portfolio in minutes, and how to structure yours around that reality.",
    author: "OrigoHOST Career Development",
    date: "2026-06-16",
    readingTime: "5 min",
    tags: ["career", "portfolio"],
  },
  {
    title: "Designing systems that scale — session deck",
    slug: "designing-systems-that-scale-deck",
    type: "Presentation",
    category: "Software Engineering",
    description: "Slides from the Knowledge Sharing Series session on service boundaries, caching and reliability.",
    author: "OrigoHOST Programs",
    date: "2026-09-13",
    readingTime: "24 slides",
    tags: ["system-design", "reliability"],
  },
  {
    title: "Practical threat modelling worksheet",
    slug: "practical-threat-modelling-worksheet",
    type: "Template",
    category: "Cybersecurity",
    description: "A one-page worksheet for running a lightweight threat model on an application you already own.",
    author: "OrigoHOST CyberForge",
    date: "2026-09-28",
    readingTime: "1 page",
    tags: ["security", "threat-modelling", "cyberforge"],
  },
  {
    title: "Evaluating AI features before you ship them",
    slug: "evaluating-ai-features",
    type: "Article",
    category: "AI",
    description: "Why evaluation matters more than demos, and a minimal evaluation setup for small teams.",
    author: "OrigoHOST Research",
    date: "2026-08-05",
    readingTime: "8 min",
    tags: ["ai", "evaluation"],
  },
  {
    title: "Open source contribution paths — session recording",
    slug: "open-source-contribution-paths-recording",
    type: "Recording",
    category: "Open Source",
    description: "Full recording of the July 2026 knowledge-sharing session. Publishing in progress.",
    author: "OrigoHOST Programs",
    date: "2026-07-19",
    readingTime: "75 min",
    tags: ["recording", "open-source"],
  },
  {
    title: "Community project: chapter event toolkit",
    slug: "chapter-event-toolkit",
    type: "Project",
    category: "Community",
    description: "The templates and runbooks chapters use to plan, promote and report an event.",
    author: "OrigoHOST Community",
    date: "2026-08-11",
    readingTime: "Toolkit",
    tags: ["chapters", "operations"],
  },
  {
    title: "Reading group notes: applied machine learning",
    slug: "reading-group-applied-ml",
    type: "Research",
    category: "Research",
    description: "Community notes from the applied ML reading group, including papers discussed and takeaways.",
    author: "OrigoHOST Research",
    date: "2026-08-24",
    readingTime: "11 min",
    tags: ["research", "ml"],
  },
];

export const resourceTypes: Resource["type"][] = [
  "Article",
  "Guide",
  "Presentation",
  "Recording",
  "Research",
  "Project",
  "Template",
];

export const resourceCategories = [
  "Open Source",
  "Career",
  "Software Engineering",
  "Cybersecurity",
  "AI",
  "Community",
  "Research",
];
