import {
  LayoutDashboard,
  Users,
  Calendar,
  Briefcase,
  FileText,
  MessageSquare,
  Award,
  Image as ImageIcon,
  Building2,
  BookOpen,
  HelpCircle,
  Link2,
  Settings,
  LogOut,
  ChevronLeft,
  ChevronRight,
  Search,
  ShieldAlert,
  Cpu,
  Bot,
  CreditCard,
  Terminal,
  UserCircle,
  Megaphone,
  BarChart3,
  Grip,
} from "lucide-react";

export function slugify(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");
}

export const WORKSPACES = [
  {
    name: "Dashboard",
    icon: LayoutDashboard,
    items: [
      { label: "Overview", href: "/admin", icon: LayoutDashboard },
      { label: "Search (Cmd+K)", href: "#search", icon: Search },
    ],
  },
  {
    name: "Operations",
    icon: Settings,
    items: [
      "Users",
      "Students",
      "Organizations",
      "Host Requests",
      "Schedule Calls",
      "Sponsors",
      "Recruiters",
      "Mentors",
      "Volunteers",
      "Speakers",
      "Admins",
      "Roles",
      "Permissions",
      "Registration Management",
      "Verification Center",
      "Activity Timeline",
      "Sessions",
      "Device Manager",
      "Audit Logs",
      "Recycle Bin",
    ],
  },
  {
    name: "Community",
    icon: Users,
    items: [
      "Community Members",
      "Groups",
      "Communities",
      "Forums",
      "Discussions",
      "Mentorship",
      "Campus Ambassador",
      "Leaderboard",
      "Achievements",
      "Badges",
      "Certificates",
      "Volunteer Management",
      "Announcements",
      "Community Analytics",
    ],
  },
  {
    name: "Content",
    icon: FileText,
    items: [
      "CMS",
      "Homepage",
      "Landing Pages",
      "Page Builder",
      "Blog",
      "Categories",
      "Authors",
      "Gallery",
      "Media Library",
      "Videos",
      "Resources",
      "Testimonials",
      "FAQs",
      "Menus",
      "Footer",
      "Navigation",
      "Forms Builder",
      "Popup Builder",
      "Banner Manager",
    ],
  },
  {
    name: "Events",
    icon: Calendar,
    items: [
      "Events",
      "Categories",
      "Schedules",
      "Venues",
      "Speakers",
      "Sponsors",
      "Partners",
      "Registration",
      "Attendance",
      "QR Check-in",
      "QR Tickets",
      "Certificates",
      "Feedback",
      "Reviews",
      "Event Gallery",
      "Livestream",
      "Calendar",
      "Reports",
    ],
  },
  {
    name: "Recruitment",
    icon: Briefcase,
    items: [
      "Companies",
      "Interview Pipeline",
      "Resume Database",
      "Resume Screening",
      "Offer Letters",
      "Rejected",
      "Analytics",
      "Reports",
    ],
  },
  {
    name: "Marketing",
    icon: Megaphone,
    items: [
      "Newsletter",
      "Subscribers",
      "Campaigns",
      "Email Templates",
      "Announcement Center",
      "Notifications",
      "Popup Campaigns",
      "SEO Manager",
      "Social Posts",
      "Referral Program",
      "Coupon Manager",
    ],
  },
  {
    name: "Analytics",
    icon: BarChart3,
    items: [
      "Dashboard",
      "Users",
      "Traffic",
      "Events",
      "Jobs",
      "Organizations",
      "Countries",
      "Cities",
      "Devices",
      "Browsers",
      "Conversions",
      "Funnels",
      "Retention",
      "Reports",
      "Heatmaps",
      "Realtime",
      "Exports",
    ],
  },
  {
    name: "AI Center",
    icon: Bot,
    items: [
      "AI Dashboard",
      "AI Search",
      "AI Chatbot",
      "AI Career Advisor",
      "AI Resume Review",
      "AI Analytics",
      "AI Content Generator",
      "AI Moderation",
      "Prompt Library",
      "Prompt Templates",
      "AI Logs",
      "Token Usage",
      "AI Settings",
    ],
  },
  {
    name: "Finance",
    icon: CreditCard,
    items: [
      "Payments",
      "Invoices",
      "Transactions",
      "Refunds",
      "Subscriptions",
      "Revenue",
      "Sponsors",
      "Donations",
      "Taxes",
      "Reports",
    ],
  },
  {
    name: "System",
    icon: Cpu,
    items: [
      "Settings",
      "Branding",
      "Logo",
      "Theme",
      "Email",
      "SMTP",
      "Domains",
      "Storage",
      "Localization",
      "Timezone",
      "Maintenance",
      "Feature Flags",
      "Security",
      "Backups",
      "Restore",
      "System Health",
      "Integrations",
    ],
  },
  {
    name: "Developer",
    icon: Terminal,
    items: [
      "API Explorer",
      "API Keys",
      "Webhook Manager",
      "Webhook Logs",
      "SQL Explorer",
      "Database Browser",
      "Storage Browser",
      "Cron Jobs",
      "Queue Manager",
      "Error Logs",
      "Activity Logs",
      "Deployment Logs",
      "Environment Variables",
      "Feature Flags",
      "Developer Tools",
    ],
  },
  {
    name: "Personal",
    icon: UserCircle,
    items: [
      "My Profile",
      "Appearance",
      "Preferences",
      "Notifications",
      "Connected Accounts",
      "API Tokens",
      "Sessions",
      "Security",
      "Help",
      "Feedback",
    ],
  },
];

export const WORKSPACE_OVERRIDES: Record<string, string> = {
  users: "/admin/users",
  "operations/sponsors": "/admin/sponsors",
  "audit-logs": "/admin/audit",
  settings: "/admin/settings",
  newsletter: "/admin/newsletter",
  "seo-manager": "/admin/seo",
  events: "/admin/events",
  pages: "/admin/pages",
  certificates: "/admin/certificates",
  partners: "/admin/partners",
  testimonials: "/admin/testimonials",
  messages: "/admin/messages",
  gallery: "/admin/gallery",
  blog: "/admin/blog",
  faq: "/admin/faq",
  navigation: "/admin/navigation",
  registration: "/admin/event-registrations",
  "schedule-calls": "/admin/schedule-calls",
};
